baseURL = 'http://localhost/'
languageCode = 'en-us'
title = 'Up Business'
theme = 'up-business-theme'


[params]
title = "Up Business"
description = "We specialize in providing services to desing websites, applications, build and maintain business for customers."
images = ["images/hero-image.png"]
contact = [
    "trungkienspktnd@gamail.com",
    "207.555.0119"
  ]